# This is a basic workflow to help you get started with Actions

name: Pull Request Unit Tests

# Controls when the action will run. 
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unitTests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      WORKING_DIRECTORY: ./my-app
      MESSAGE: Thank you for coming to my peer to peer

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.16.1

      - name: Install Dependencies
        run: npm install
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Run Unit Tests
        run: npm run test
        working-directory: ${{env.WORKING_DIRECTORY}}
        
      - name: Conditionally Show Message
        if: github.head_ref == 'triggerAction'
        run: echo $MESSAGE
